from enum import Enum

class QuestionType(str, Enum):
    CONCEPT = "CONCEPT"
    IMPLEMENTATION = "IMPLEMENTATION"
    DEBUGGING = "DEBUGGING"
    TRADEOFF = "TRADEOFF"
    SCALING = "SCALING"
    SYSTEM_DESIGN = "SYSTEM_DESIGN"
    PRODUCTION = "PRODUCTION"
    CAPSTONE = "CAPSTONE"

class ProbeType(str, Enum):
    CLARIFY = "CLARIFY"
    WHY = "WHY"
    TRADEOFF = "TRADEOFF"
    SCALING = "SCALING"
    DEBUGGING = "DEBUGGING"
    PRODUCTION = "PRODUCTION"
    ALTERNATIVE = "ALTERNATIVE"
